[build]
target = "index.html"
dist = "dist"
# Public URL will be set by GitHub Actions
# Don't set public-url here - let CI handle it

[watch]
watch = ["src", "styles"]
ignore = ["dist", "target"]

[serve]
address = "127.0.0.1"
port = 8080
open = true

# CSS compression
[build.sass]
style = "compressed"
